[package]
name = "Bachelor-Assurance"
version = "0.1.0"
edition = "2024"

[lib]
name = "bachelor_assurance"

[dependencies]
hax-lib = { git = "https://github.com/hacspec/hax", version = "0.3.6" }
libcrux = { version = "0.0.2-pre.2", features = ["rand"] }
rand = "0.10.0"
stacker = "0.1.24"
rayon = "1.12.0"
lib = "0.0.2"
sha3 = "0.10.0"
digest = "0.11.3"

[target."cfg(hax)".dependencies]
hax-lib = { git = "https://github.com/hacspec/hax", version = "0.3.6" }

[features] # when changing verison, changes to constants also needs to be made
lambda_128s = [] # lambda = 128, tau = 11, ell = 1600
lambda_128f = [] # lambda = 128, tau=16, ell = 1600
lambda_192s = [] # lambda = 192, tau = 16, ell = 3264
lambda_192f = [] # lambda = 192, tau=24, ell = 3264
lambda_256s = [] # lambda = 256, tau = 22, ell = 4000
lambda_256f = [] # lambda = 256, tau = 32, ell = 4000
default = ["lambda_256f"]
hax = []

