#![allow(non_upper_case_globals)]
use crate::utils::prg::prg;
use crate::utils::constants::{iv_bytes, k_1, lambda_bytes, lambda_bytes_times_two};
use crate::utils::types::{sized_array_16, sized_option_array, Log2Number};

// a function for generating size_pow random values, as ggm tree
pub fn get_leaves_node_from_root<const size_pow: usize>(r: &[u8; lambda_bytes], iv: [u8; iv_bytes], k: usize) -> sized_array_16<size_pow>{
    // size of random values
    let mut leaves = [[0u8;lambda_bytes]; size_pow];
    // first value needed for generating values
    leaves[0] = *r;
    // should hold that log_2(size_pow) = k
    for i in 1..(k + 1) {
        // save current leaves, they are to be used to generate the next layer of random values
        let current_leaves = leaves;
        // iterating over the size of the next layer so in the first iteration 2^1 >> 1 = 1, since each iteration generates two values
        // so for the first value we get 2 new values
        // for the two second values, we get four new values
        for j in 0..(2_i32.pow(i as u32) >> 1) {
            // get the value to be used to generate the next two values
            let ran_value = current_leaves[j as usize];
            // a place to place the next two values
            let mut nodes = [0u8; lambda_bytes_times_two];
            // randomly generating the new values
            prg(ran_value, iv, &mut nodes);

            // get values from each part of the randomly generated value
            let left_node_value : [u8;lambda_bytes]= nodes[..lambda_bytes].try_into().unwrap();
            let right_node_value : [u8;lambda_bytes] = nodes[lambda_bytes..].try_into().unwrap();

            // store the two new values
            leaves[(j << 1) as usize].copy_from_slice(&left_node_value);
            leaves[((j << 1) + 1) as usize].copy_from_slice(&right_node_value);
        }
    }
    // returns all the values
    leaves
}

// should return all siblign nodes, from path of root to hidden value at index b
pub fn get_cop<const size: usize>(r: [u8;lambda_bytes], iv: [u8;iv_bytes], b: u64) -> sized_array_16<size> {
    // create array for inserting sibling node values
    let mut cop = [[0u8; lambda_bytes]; size];
    // the current node represents, the node that should not be contained in cop
    // but the node that is parent, to the next current node, and a node that should be contained in cop
    let mut current_node = r;
    // a value i to index over
    let mut i : i128 = (size - 1) as i128;
    // starting from the upper layer and moving down, that is why we start with i = k-1
    while i >= 0 {
        // finding if the path to the hidden node, is to the left of the current node layer
        // if b is 0, then the left node of the root node, is on the path to the hidden node
        // if b is 0, then is_left is always true
        let is_left = get_if_left(i as u64, b as u64);

        // generating the two child nodes of the current node
        let mut nodes = [0u8; lambda_bytes_times_two];
        prg(current_node, iv, &mut nodes);

        // get values from each child of the current node
        let left_node_value : [u8;lambda_bytes]= nodes[..lambda_bytes].try_into().unwrap();
        let right_node_value : [u8;lambda_bytes] = nodes[lambda_bytes..].try_into().unwrap();


        if is_left {
            // if is_left == true, then the right node is saved, since it will be the sibling node
            // of one of the nodes from the path of root to hidden node
            current_node = left_node_value;
            cop[(size-(i as usize)-1) as usize] = right_node_value;
        } else {
            // if is_left == false, then the left node is saved, since it will be the sibling node
            // of one of the nodes from the path of root to hidden node
            current_node = right_node_value;
            cop[(size-(i as usize)-1) as usize] = left_node_value;
        }
        // moving a layer down
        i -= 1;
    }
    // returning cop
    cop
}

// a function for seeing if a leaf index is to the left (or right) to a certain level
// i.e. if the index is 0, then it will always be to the left
pub fn get_if_left(level : u64, index : u64) -> bool{
    // we save index and level in mutable variables
    let mut index = index;
    // the index structure is that each level has its own indexing
    // so each level starts at zero, we therefore get the index of the child to the node at level
    // where the index, is the node on the path from root to index node
    index = index >> level;

    if index % 2 == 1 { // if odd the node is on the right
        false
    } else { // if even it is on the left
        true
    }
}
// this receives the cop, generated by cop, iv and a index
// this function wants to generate all but one of the leaves
pub fn get_leaves_from_cop_and_b<const size : usize, const size_pow : usize>(cop : &sized_array_16<size>, iv : [u8;iv_bytes], b: u64) -> sized_option_array<size_pow> {
    // some initialising of values
    // a place to store the leaves, it is initialized with None, since one of the leaves are the hidden value
    let mut leaves = [None; size_pow];
    // updating such that from current start to current end, is the leaves missing
    let mut current_start = 0;
    let mut current_end = size_pow;
    // how many leaves are being added in the current iteration, for the first iteration it is size_pow/2
    let mut match_value = Log2Number::wrap(size_pow >> 1);
    // a inner helper function, supposed to generate leaves, based on the current node
    fn cop_helper<const N: usize, const size_pow: usize>(c: &[u8; lambda_bytes], leaves: &mut [Option<[u8; lambda_bytes]>; size_pow], iv: [u8; iv_bytes], b: u64, current_start: &mut usize, current_end: &mut usize) {
        // N is the amount of leaves being generated, so d is the amount of levels, this tree shall have
        let d = N.ilog2() as usize;
        // using priveous function to generate leaves
        let leaves_to_add = get_leaves_node_from_root::<N>(c, iv, d);
        // using the left functionality, to update the tree
        // this functionality used the currentstart and currentend, to check which indexes the N leaves shall be placed at
        // it therefore also update current end or current start
        if get_if_left(d as u64, b){
            for i in (*current_start+N)..*current_end {
                leaves[i] = Some(leaves_to_add[i-(*current_start+N)]);
            }
            *current_end -= N;
        } else {
            for i in 0..N {
                leaves[i+*current_start] = Some(leaves_to_add[i]);
            }
            *current_start += N;
        }
    }
    // Matching we each of the different values that it can be, the highest value is 2048, since k_0 is at most 12
    for c in cop {
        match match_value {
            Log2Number::one => {cop_helper::<1, size_pow>(c, &mut leaves, iv, b, &mut current_start, &mut current_end);}
            Log2Number::two => {cop_helper::<2, size_pow>(c, &mut leaves, iv, b, &mut current_start, &mut current_end);}
            Log2Number::four => {cop_helper::<4, size_pow>(c, &mut leaves, iv, b, &mut current_start, &mut current_end);}
            Log2Number::eight => {cop_helper::<8, size_pow>(c, &mut leaves, iv, b, &mut current_start, &mut current_end);}
            Log2Number::sixteen => {cop_helper::<16, size_pow>(c, &mut leaves, iv, b, &mut current_start, &mut current_end);}
            Log2Number::thirtytwo => {cop_helper::<32, size_pow>(c, &mut leaves, iv, b, &mut current_start, &mut current_end);}
            Log2Number::sixtyfour => {cop_helper::<64, size_pow>(c, &mut leaves, iv, b, &mut current_start, &mut current_end);}
            Log2Number::onehundredandtwentyeight => {cop_helper::<128, size_pow>(c, &mut leaves, iv, b, &mut current_start, &mut current_end);}
            Log2Number::twohundredandfiftysix => {cop_helper::<256, size_pow>(c, &mut leaves, iv, b, &mut current_start, &mut current_end);}
            Log2Number::fivehundredandtwelve => {cop_helper::<512, size_pow>(c, &mut leaves, iv, b, &mut current_start, &mut current_end);}
            Log2Number::onethousandandtwentyfour => {cop_helper::<1024, size_pow>(c, &mut leaves, iv, b, &mut current_start, &mut current_end);}
            Log2Number::twothousandsandfortyeight => {cop_helper::<2048, size_pow>(c, &mut leaves, iv, b, &mut current_start, &mut current_end);}
        }
        if match_value.value() > 1 { match_value = match_value.log_reduce() }
    }
    leaves
}

